
package top_down;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "FishNotFoundEx", targetNamespace = "http://service/")
public class FishNotFoundEx_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FishNotFoundEx faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FishNotFoundEx_Exception(String message, FishNotFoundEx faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FishNotFoundEx_Exception(String message, FishNotFoundEx faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: top_down.FishNotFoundEx
     */
    public FishNotFoundEx getFaultInfo() {
        return faultInfo;
    }

}
